.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. miguelkoin_qt test_miguelkoin_qt
clean: FORCE
	$(MAKE) -C .. miguelkoin_qt_clean test_miguelkoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_miguelkoin_qt_check
miguelkoin-qt miguelkoin-qt.exe: FORCE
	 $(MAKE) -C .. miguelkoin_qt
